name: Build on push

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - id: var
        name: Setup variables
        run: echo "commit_hash=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Use gradle cache for faster builds
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
      - name: Validate AW
        run: ./gradlew validateAccessWidener
      - name: Build with Gradle
        run: ./gradlew build
        env:
          POWAH_VERSION: vgit-${{ steps.var.outputs.commit_hash }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: powah ${{ steps.var.outputs.commit_hash }} [FABRIC]
          path: fabric/build/libs/Powah-git-${{ steps.var.outputs.commit_hash }}.jar
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: powah ${{ steps.var.outputs.commit_hash }} [FORGE]
          path: forge/build/libs/Powah-git-${{ steps.var.outputs.commit_hash }}.jar
